language: cpp

compiler:
 - gcc
 
addons:
 apt:
  packages:
   - cmake
   - cmake-data


before_install:
  - pip install --user cpp-coveralls
script:
  - ./configure --enable-gcov && make && make check
after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
