language: cpp

compiler:
 - gcc
 
addons:
 apt:
  packages:
   - cmake
   - cmake-data


before_install:
  - pip install --user cpp-coveralls
script:
  - cmake -H. -B_build -DBUILD_TESTS=ON
  - cmake --build _build
  - cmake --build _build --target test -- ARGS=--verbose
  - cd _build
  - ./check --enable-gcov 
after_success:
  - coveralls --exclude lib --exclude check --gcov-options '\-lp'
